with open("src/app/(auth)/onboarding/page.tsx", "r", encoding="utf-8") as f:
    content = f.read()

# Mettre a jour les couleurs principales
content = content.replace("background: '#F7F8FA'", "background: '#f5f3ef'")
content = content.replace("background: '#0A3D26'", "background: '#1a1a1a'")
content = content.replace("color: '#0A3D26'", "color: '#1a1a1a'")
content = content.replace("borderColor = '#0A3D26'", "borderColor = '#1a1a1a'")
content = content.replace("border: '1px solid #EEF0F3'", "border: '1px solid #d4c5b0'")
content = content.replace("border: '1.5px solid #EEF0F3'", "border: '1.5px solid #d4c5b0'")
content = content.replace("borderColor = '#E2E8F0'", "borderColor = '#d4c5b0'")
content = content.replace("border: '1.5px solid #E2E8F0'", "border: '1.5px solid #d4c5b0'")
content = content.replace("boxShadow: '0 4px 24px rgba(0,0,0,0.06)'", "boxShadow: '0 2px 12px rgba(26,26,26,0.06)'")
content = content.replace("borderRadius: 16", "borderRadius: 8")
content = content.replace("borderRadius: 10", "borderRadius: 4")
content = content.replace("borderRadius: 8", "borderRadius: 4")
content = content.replace("color: '#94A3B8'", "color: '#8b7355'")
content = content.replace("color: '#64748B'", "color: '#4a5568'")
content = content.replace("color: '#475569'", "color: '#4a5568'")
content = content.replace("background: '#E2E8F0'", "background: '#e8e3d8'")
content = content.replace("color: '#94A3B8'", "color: '#8b7355'")
content = content.replace("border: '1px solid #FCD34D'", "border: '1px solid #b8860b'")
content = content.replace("background: '#FEF3C7'", "background: '#fdf8ec'")
content = content.replace("color: '#92400E'", "color: '#b8860b'")
content = content.replace("border: '1px solid #A7F3D0'", "border: '1px solid #2d5016'")
content = content.replace("background: '#F0FDF4'", "background: '#f0f4ec'")
content = content.replace("color: '#065F46'", "color: '#2d5016'")
content = content.replace("src=\"/logo.png\"", "src=\"/logo_ethys.png\"")
content = content.replace("fontFamily: \"'DM Sans', sans-serif\"", "fontFamily: \"'Inter', system-ui, sans-serif\"")

with open("src/app/(auth)/onboarding/page.tsx", "w", encoding="utf-8") as f:
    f.write(content)
print("Done onboarding")
